# Generated by Django 4.2.26 on 2026-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template Name', max_length=150)),
                ('body', models.TextField(help_text='Message body template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
