# Generated by Django 4.2.30 on 2026-07-27 11:43

from django.db import migrations, models


def deduplicate_template_names(apps, schema_editor):
    Template = apps.get_model('sms', 'SMSTemplate')
    seen = set()
    for template in Template.objects.order_by('id'):
        base = template.name
        candidate = base
        suffix = 2
        while candidate in seen:
            candidate = f'{base} ({suffix})'
            suffix += 1
        if candidate != template.name:
            template.name = candidate
            template.save(update_fields=['name'])
        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smstemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('PARTIAL', 'Partially sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=15),
        ),
        migrations.RunPython(deduplicate_template_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='smstemplate',
            name='name',
            field=models.CharField(help_text='Template Name', max_length=150, unique=True),
        ),
    ]
