# Generated by Django 4.2.30 on 2026-04-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('STAFF', 'Staff'), ('ALUMNI', 'Alumni')], default='PARENT', max_length=10)),
                ('relationship_type', models.CharField(blank=True, help_text='E.g., Mother, Father, Guardian', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(help_text='Variables allowed: {name}, {balance}, {date}, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Grade 7 Parents, All Staff', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contacts', models.ManyToManyField(help_text='Members of this group', related_name='groups', to='core.contact')),
            ],
        ),
    ]
