# Generated by Django 4.2.26 on 2026-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff'), ('ALUMNI', 'Alumni')], default='PARENT', max_length=10),
        ),
    ]
