# Generated by Django 4.2.30 on 2026-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff')], default='PARENT', max_length=10),
        ),
    ]
