# Generated by Django 4.2.30 on 2026-07-27 11:43

from django.db import migrations


def copy_templates(apps, schema_editor):
    OldTemplate = apps.get_model('core', 'SMSTemplate')
    NewTemplate = apps.get_model('sms', 'SMSTemplate')
    for template in OldTemplate.objects.all():
        name = template.name
        suffix = 2
        while NewTemplate.objects.filter(name=name).exists():
            name = f'{template.name} ({suffix})'
            suffix += 1
        NewTemplate.objects.create(name=name, body=template.content)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_alumni_student'),
        ('sms', '0003_alter_smscampaign_status_alter_smstemplate_name'),
    ]

    operations = [
        migrations.RunPython(copy_templates, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SMSTemplate',
        ),
    ]
