"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


DEBUG = env_bool('DEBUG', False)
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-only'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG=False.')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Render uses a proxy that handles SSL termination.
# This setting tells Django to trust the HTTP_X_FORWARDED_PROTO header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Add any additional origins from environment variables
env_trusted_origins = os.getenv('CSRF_TRUSTED_ORIGINS')
if env_trusted_origins:
    CSRF_TRUSTED_ORIGINS.extend(env_trusted_origins.split(','))
else:
    # Default Render URL if not explicitly provided
    CSRF_TRUSTED_ORIGINS.append('https://lofty-creek.onrender.com')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_summernote',
    'public',
    'core',
    'sms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'public.context_processors.site_links',
                'sms.context_processors.balance_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
if AWS_STORAGE_BUCKET_NAME:
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'af-south-1')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {'location': 'media'},
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 300
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'

# Email notifications for public website inquiries
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'info@loftycreekchristianschool.org',
)
INQUIRY_NOTIFICATION_EMAIL = os.getenv(
    'INQUIRY_NOTIFICATION_EMAIL',
    'info@loftycreekchristianschool.org',
)

# Optional public links. Empty values are hidden instead of rendering dead links.
FACEBOOK_URL = os.getenv(
    'FACEBOOK_URL',
    'https://www.facebook.com/share/18xADNP3RU/?mibextid=wwXIfr',
)
INSTAGRAM_URL = os.getenv(
    'INSTAGRAM_URL',
    'https://www.instagram.com/loftycreekchristianschool',
)
YOUTUBE_URL = os.getenv(
    'YOUTUBE_URL',
    'https://youtube.com/@loftycreekchristianschool1985?si=vI3aeh-iqjMF4u4T',
)
PRIVACY_POLICY_URL = os.getenv('PRIVACY_POLICY_URL', '/privacy-policy/')
TERMS_OF_SERVICE_URL = os.getenv('TERMS_OF_SERVICE_URL', '/terms-of-service/')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Africa's Talking API Credentials
AFRICASTALKING_USERNAME = os.getenv('AFRICASTALKING_USERNAME', 'sandbox')
AFRICASTALKING_API_KEY = os.getenv('AFRICASTALKING_API_KEY', '')
AFRICASTALKING_SENDER_ID = os.getenv('AFRICASTALKING_SENDER_ID', None)
AFRICASTALKING_WEBHOOK_TOKEN = os.getenv('AFRICASTALKING_WEBHOOK_TOKEN', '')

# Background SMS processing. Local development can opt in by setting this true.
SMS_SEND_ASYNC = env_bool('SMS_SEND_ASYNC', not DEBUG)
REDIS_URL = os.getenv('REDIS_URL', '')
CELERY_BROKER_URL = REDIS_URL or 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = {
    'send-due-sms-campaigns': {
        'task': 'sms.tasks.send_due_campaigns',
        'schedule': 60.0,
    },
}

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }


# ---------------------------------------------------------------------------
# Jazzmin Admin Dashboard – Lofty Creek Christian School
# ---------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    # ── Branding ──────────────────────────────────────────────────────────
    "site_title": "LCCS Admin",
    "site_header": "Lofty Creek Christian School",
    "site_brand": "LCCS",
    "site_logo": "img/logo_2.png",
    "login_logo": "img/logo_2.png",
    "site_icon": None,
    "welcome_sign": "Welcome to the LCCS Administration Portal",
    "copyright": "Lofty Creek Christian School",

    # ── Top links (quick nav shortcuts) ───────────────────────────────────
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📡 SMS Dashboard", "url": "/sms/", "new_window": False},
        {"name": "🌐 School Website", "url": "/", "new_window": True},
    ],

    # ── User menu (top-right avatar dropdown) ─────────────────────────────
    "usermenu_links": [
        {"name": "📡 SMS Dashboard", "url": "/sms/", "icon": "fas fa-satellite-dish"},
        {"model": "auth.user"},
    ],

    # ── Sidebar ───────────────────────────────────────────────────────────
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Order the sidebar apps and models explicitly
    "order_with_respect_to": [
        "auth",
        "public",
        "public.BlogPost",
        "public.GalleryPhoto",
        "public.ContactMessage",
        "core",
        "core.Contact",
        "core.ContactGroup",
        "sms",
        "sms.SMSCampaign",
        "sms.SMSMessage",
        "sms.SMSTemplate",
    ],

    # Custom sidebar links per app
    "custom_links": {
        "sms": [
            {
                "name": "📡 SMS Dashboard",
                "url": "/sms/",
                "icon": "fas fa-tachometer-alt",
            },
            {
                "name": "✍️ Broadcast Hub",
                "url": "/sms/compose/",
                "icon": "fas fa-paper-plane",
            },
            {
                "name": "👥 Contact Manager",
                "url": "/sms/contacts/",
                "icon": "fas fa-address-book",
            },
            {
                "name": "📋 Message Templates",
                "url": "/sms/templates/",
                "icon": "fas fa-file-alt",
            },
        ],
    },

    # ── Icons ─────────────────────────────────────────────────────────────
    "icons": {
        "auth":                        "fas fa-users-cog",
        "auth.user":                   "fas fa-user",
        "auth.Group":                  "fas fa-layer-group",
        "public.BlogPost":             "fas fa-blog",
        "public.GalleryPhoto":         "fas fa-images",
        "public.ContactMessage":       "fas fa-envelope-open-text",
        "core.Contact":                "fas fa-address-card",
        "core.ContactGroup":           "fas fa-users",
        "sms.SMSCampaign":             "fas fa-broadcast-tower",
        "sms.SMSMessage":              "fas fa-envelope",
        "sms.SMSTemplate":             "fas fa-scroll",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── UI options ────────────────────────────────────────────────────────
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "custom_css": "css/admin.css",

    # ── Search ────────────────────────────────────────────────────────────
    "search_model": ["auth.user", "core.Contact"],

    # ── Change-view actions ───────────────────────────────────────────────
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user":  "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}

# ---------------------------------------------------------------------------
# Logging Configuration. Hosted services should write logs to stdout.
# ---------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} [{module}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'sms': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
