# Generated by Django 4.2.30 on 2026-04-30 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Academics', 'Academics'), ('Activities', 'Activities'), ('Events', 'Events'), ('Announcements', 'Announcements'), ('Faith', 'Faith & Values'), ('Other', 'Other')], default='Other', max_length=30)),
                ('excerpt', models.TextField(help_text='Short summary shown on the cards (max 500 chars)', max_length=500)),
                ('content', models.TextField(help_text='Full article content. HTML is supported.')),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended size: 800×500 px', null=True, upload_to='blog/')),
                ('author', models.CharField(default='LCCS Staff', max_length=100)),
                ('published', models.BooleanField(default=False, help_text='Tick to make this post visible on the website')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
