# Generated by Django 4.2.30 on 2026-04-30 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('all', 'All'), ('campus', 'Campus'), ('academics', 'Academics'), ('events', 'Events'), ('sports', 'Sports')], default='campus', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('visible', models.BooleanField(default=True, help_text='Uncheck to hide from the gallery')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
