# Generated by Django 4.2.30 on 2026-07-27 11:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 800×500 px', null=True, upload_to='blog/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[core.validators.validate_image_size]),
        ),
    ]
